version: '3.1'

services:

  mongo:
    container_name: mongo-db
    image: mongo
    #restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: pass
    networks: 
      - mongo-compose-network  
    ports:
      - 127.0.0.1:27017:27017  

  mongo-express:
    container_name: mongo-exp
    image: mongo-express
    #restart: always
    networks: 
      - mongo-compose-network
    ports:
      - 127.0.0.1:8081:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_PORT: 27017
      #ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

networks:
  mongo-compose-network:
    driver: bridge      